driver:Collection Set HashSet List ArrayList LinkedList Queue Iterator 161044072_main
	g++ Collection.o Set.o HashSet.o List.o ArrayList.o LinkedList.o Queue.o Iterator.o 161044072_main.o -o driver

Collection:
	g++ -c Collection.cpp -o Collection.o -std=c++11 
Set:
	g++ -c Set.cpp -o Set.o -std=c++11
HashSet:
	g++ -c HashSet.cpp -o HashSet.o -std=c++11		
List:
	g++ -c List.cpp -o List.o -std=c++11	
ArrayList:
	g++ -c ArrayList.cpp -o ArrayList.o -std=c++11
LinkedList:
	g++ -c LinkedList.cpp -o LinkedList.o -std=c++11	
Queue:
	g++ -c Queue.cpp -o Queue.o -std=c++11	
Iterator:
	g++ -c Iterator.cpp -o Iterator.o -std=c++11		
161044072_main:
	g++ -c 161044072_main.cpp -o 161044072_main.o -std=c++11



