driver:rectangle triangle circle composedShape 161044072_main
	g++ rectangle.o triangle.o circle.o composedShape.o 161044072_main.o -o driver

rectangle:
	g++ -c rectangle.cpp -o rectangle.o -std=c++11
triangle:
	g++ -c triangle.cpp -o triangle.o -std=c++11
circle:
	g++ -c circle.cpp -o circle.o -std=c++11
composedShape:
	g++ -c composedShape.cpp -o composedShape.o -std=c++11
161044072_main:
	g++ -c 161044072_main.cpp -o 161044072_main.o -std=c++11



