driver:rectangle triangle circle polygon PolygonVect PolygonDyn composedShape shape 161044072_main
	g++ rectangle.o triangle.o circle.o polygon.o PolygonVect.o PolygonDyn.o composedShape.o shape.o 161044072_main.o -o driver

rectangle:
	g++ -c rectangle.cpp -o rectangle.o -std=c++11
triangle:
	g++ -c triangle.cpp -o triangle.o -std=c++11
circle:
	g++ -c circle.cpp -o circle.o -std=c++11
polygon:
	g++ -c polygon.cpp -o polygon.o -std=c++11
PolygonVect:
	g++ -c PolygonVect.cpp -o PolygonVect.o -std=c++11	
PolygonDyn:
	g++ -c PolygonDyn.cpp -o PolygonDyn.o -std=c++11
composedShape:
	g++ -c composedShape.cpp -o composedShape.o -std=c++11
shape:
	g++ -c shape.cpp -o shape.o -std=c++11
161044072_main:
	g++ -c 161044072_main.cpp -o 161044072_main.o -std=c++11



